[package]
name = "cargo-auto"
version = "2024.225.1841"
authors = ["bestia.dev"]
homepage = "https://bestia.dev"
edition = "2021"
description = "cargo-auto - automation tasks coded in Rust language for the workflow of Rust projects"
repository = "https://github.com/bestia-dev/cargo-auto"
readme = "README.md"
license = "MIT"
# Keyword must be only one word: lowercase letters, hyphens(-) or numbers, less then 35 characters.
keywords = ["maintained", "ready-for-use", "rustlang", "make"]
categories = ["command-line-interface","development-tools::build-utils","development-tools::cargo-plugins"]
# publish as a cargo tool. Only this files.
publish = true
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/*"
]

[dependencies]
lazy_static="1.4.0"
base64ct = {version = "1.6.0", features = ["alloc"] }
json5 = "0.4.1"
serde = { version = "1.0.196", features = ["derive"] }
image = "0.24.8"
ico = "0.3.0"
ring = "0.17.7"
data-encoding = "2.5.0"
anyhow="1.0.79"
serde_derive = "1.0.196"
serde_json = "1.0.113"
