[package]
name = "cargo-auto"
version = "2024.220.2216"
authors = ["bestia.dev"]
homepage = "https://bestia.dev"
edition = "2021"
description = "cargo-auto - automation tasks written in Rust language for the build process of Rust projects"
repository = "https://github.com/bestia-dev/cargo-auto"
readme = "README.md"
license = "MIT"
keywords = ["Rust", "make"]
categories = ["development-tools::build-utils"]
# publish as a cargo tool. Only this files.
publish = true
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/*"
]

[dependencies]
lazy_static="1.4.0"
base64ct = {version = "1.6.0", features = ["alloc"] }
json5 = "0.4.1"
serde = { version = "1.0.196", features = ["derive"] }
image = "0.24.8"
ico = "0.3.0"
ring = "0.17.7"
data-encoding = "2.5.0"
anyhow="1.0.79"
serde_derive = "1.0.196"
serde_json = "1.0.113"
