name: rust_fmt_auto_build_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_fmt_auto_build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache rust dependencies
      uses: Swatinem/rust-cache@v2.7.3
    - name: Configure sccache
      run: echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV; echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
    - name: Run sccache-cache for artifacts
      uses: mozilla-actions/sccache-action@v0.0.4
    - name: Fmt
      run: cargo fmt -- --check
    - name: Install cargo-auto
      run: cargo install --force cargo-auto
    - name: Build
      run: cargo auto build
    - name: Test
      run: cargo auto test
      
